name: Build and Push to docker hub
on:
  workflow_call:
    inputs:
      folder:
        description: 'Folder to build in'
        required: true
        type: string
      name:
        description: 'Image name'
        required: true
        type: string
      tag:
        description: 'Image tag'
        default: "latest"
        required: false
        type: string


runs:
    steps:
      - name: Build container
        run: docker build -t cubicrootxyz/${{ inputs.name }}:${{ inputs.tag }} ${{ folder }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        run: docker push cubicrootxyz/${{ inputs.name }}:${{ inputs.tag }}

