name: Build and Push to docker hub
on:
  workflow_call:
    inputs:
      folder:
        description: 'Folder to build in'
        required: true
        type: string
      name:
        description: 'Image name'
        required: true
        type: string
      tag:
        description: 'Image tag'
        default: "latest"
        required: false
        type: string


jobs:
    build_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Build container
        run: docker build -t cubicrootxyz/${{ inputs.name }}:${{ inputs.tag }} ${{ folder }}
