on:
  push:
    paths:
      - 'laravel-base/*'
      
jobs: 
  build_and_push:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
      - name: Build container
        run: docker build -t cubicrootxyz/laravel-base:latest laravel-base
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        run: docker push cubicrootxyz/laravel-base:latest
  build:
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
      - name: Build container
        run: docker build -t cubicrootxyz/laravel-base:latest laravel-base