name: Main
on:
  push:
    paths-ignore:
      - '**.md'
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - 'index.html'
jobs: 
  build_push_matrix_go:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/build_push@main
        with:
          folder: matrix-go
          name: matrix-go
          tag: latest
  build_matrix_go:
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/build@main
        with:
          folder: matrix-go
          name: matrix-go
          tag: latest
