on:
  push:
    paths:
      - 'matrix-go/*'
      
jobs: 
  build_push_matrix_go_1-16:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    env:
      GO_VERSION: 1.16
    steps:
      - uses: actions/checkout@v2
      - name: Build container
        run: docker build -t cubicrootxyz/matrix-go:$GO_VERSION -e GO_VERSION matrix-go
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        run: docker push cubicrootxyz/matrix-go:$GO_VERSION
  build_matrix_go_1-16:
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}
    env:
      GO_VERSION: 1.16
    steps:
      - uses: actions/checkout@v2
      - name: Build container
        run: docker build -t cubicrootxyz/matrix-go:$GO_VERSION -e GO_VERSION matrix-go